version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Install  Dependencies
          command: npm i
      - run:
          name: Build Server
          command: npm run build:server
      - run:
          name: Build Front-End
          command: npm run build:frontend
      - persist_to_workspace:
          root: .
          paths:
            - packages/storeFront_API/build/*
            - packages/storeFront/dist/store-front/*

  deploy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - eb/setup
      - attach_workspace:
          at: .
      - aws-s3/copy:
          arguments: --acl public-read --recursive
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: packages/storeFront/dist/store-front
          to: "s3://$S3_FRONT_END_BUCKET/"
      - run:
          name: Initialize Elastic Beanstalk Application
          command: cd packages/storeFront_API && eb init --platform node.js
      - run:
          name: Copy existing config for deployment
          command: cd packages/storeFront_API && cp build/config.yml .elasticbeanstalk/config.yml
      - run:
          name: Set Elastic Beanstalk Environment Variables
          command:
            cd packages/storeFront_API && eb setenv AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
            AWS_REGION=${AWS_REGION} \
            AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            JWT_SECRET=${JWT_SECRET} \
            PEPPER=${PEPPER} \
            RDS_HOSTNAME=${RDS_HOSTNAME} \
            RDS_PASSWORD=${RDS_PASSWORD} \
            RDS_PORT=${RDS_PORT} \
            RDS_USERNAME=${RDS_USERNAME} \
            S3_FRONT_END_BUCKET=${S3_FRONT_END_BUCKET} \
            SALT_ROUNDS=${SALT_ROUNDS} \
            SERVER_URL=${SERVER_URL}
      - run:
          name: Deploy Server to Elastic Beanstalk
          command: cd packages/storeFront_API && eb deploy --profile default
