branch-defaults:
  default:
    environment: Storefrontapi-env
    group_suffix: null
global:
  application_name: storefrontAPI
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: build/storefrontApi.zip
